sudo: true

language:
  - cpp

cache:
  ccache: true
  directories:
    - $HOME/downloads

matrix:
  include:
    #########
    # Linux Machines
    #########
    - os: linux
      env:
        - BACKEND=Intel10_64lp_seq
        - BUILD_STATIC=OFF
    - os: linux
      env:
        - BACKEND=Intel10_64lp_seq
        - BUILD_STATIC=ON
    - os: linux
      env:
        - BACKEND=Intel10_64lp
        - BUILD_STATIC=OFF
    - os: linux
      env:
        - BACKEND=Intel10_64lp
        - BUILD_STATIC=ON

    #########
    # OSx Machines
    #########
    - os: osx
      env:
        - BACKEND=Intel10_64lp_seq
        - BUILD_STATIC=OFF
    - os: osx
      env:
        - BACKEND=Intel10_64lp_seq
        - BUILD_STATIC=ON
    - os: osx
      env:
        - BACKEND=Intel10_64lp
        - BUILD_STATIC=OFF
    - os: osx
      env:
        - BACKEND=Intel10_64lp
        - BUILD_STATIC=ON


before_install:
  # Dependencies required by the CI are installed in ${TRAVIS_BUILD_DIR}/deps/
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir -p "${DEPS_DIR}"

  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      sudo dpkg --add-architecture i386
      sudo apt-get update
      sudo apt-get install -y libc6:i386 libncurses5:i386 libstdc++6:i386
    fi

  # Travis machines have 2 cores
  - JOBS=2

  - cd "${DEPS_DIR}"

  ############################################################################
  # Handle caching of downloaded files
  ############################################################################
  - export DL_DIR=$HOME/downloads
  - |
    function _download() {
        url="$1"; f="${2:-$(basename $url)}";
        if [ ! -e $DL_DIR/$f ] ; then
          mkdir -p $DL_DIR ;
          echo "Downloading: ${DL_DIR}/$f" ;
          travis_retry wget --no-verbose $url -O $DL_DIR/$f ;
        else
          echo "Reading from cache: ${DL_DIR}/$f" ;
        fi
    }
  - function download() { _download "$1" "" ; }

  ############################################################################
  # Install a recent CMake
  ############################################################################
  - CMAKE_VERSION=3.10.1
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      CMAKE_URL="https://cmake.org/files/v${CMAKE_VERSION%.[0-9]}/cmake-${CMAKE_VERSION}-Linux-x86_64.tar.gz"
      mkdir cmake && travis_retry wget --no-check-certificate -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}
    else
      brew install cmake
    fi
  - which cmake
  - cmake --version

  ############################################################################
  # Install MKL
  ############################################################################
  - |
    if [[ "${BACKEND}" == *"Intel"* ]]; then
      if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
        export MKL_INSTALL_DIR=$(pwd)/intel
        export ARCH_FNAME=l_mkl_2018.0.128.tgz
        download http://registrationcenter-download.intel.com/akdlm/irc_nas/tec/12070/${ARCH_FNAME}
        tar -xzf $DL_DIR/${ARCH_FNAME}
        cat l_mkl_2018.0.128/silent.cfg | grep -v EULA | grep -v PSET_INSTALL_DIR > silent.cfg
        echo "ACCEPT_EULA=accept" >> silent.cfg
        echo "PSET_INSTALL_DIR=${MKL_INSTALL_DIR}" >> silent.cfg
        ./l_mkl_2018.0.128/install.sh --user-mode -s ./silent.cfg
        export LD_LIBRARY_PATH="${MKL_INSTALL_DIR}/mkl/lib/intel64/:${LD_LIBRARY_PATH}"
        . ${MKL_INSTALL_DIR}/mkl/bin/mklvars.sh intel64 ilp64
      else  # Mac
        export MKL_INSTALL_DIR=/opt/intel
        export ARCH_FNAME=m_mkl_2017.4.220.dmg
        download http://registrationcenter-download.intel.com/akdlm/irc_nas/tec/12185/${ARCH_FNAME}
        hdiutil attach $DL_DIR/${ARCH_FNAME}
        cat /Volumes/m_mkl_2017.4.220/m_mkl_2017.4.220.app/Contents/MacOS/silent.cfg | grep -v EULA | grep -v PSET_INSTALL_DIR > silent.cfg
        echo "ACCEPT_EULA=accept" >> silent.cfg
        echo "PSET_INSTALL_DIR=${MKL_INSTALL_DIR}" >> silent.cfg
        sudo /Volumes/m_mkl_2017.4.220/m_mkl_2017.4.220.app/Contents/MacOS/install.sh -s ./silent.cfg
        . /opt/intel/mkl/bin/mklvars.sh intel64 ilp64
      fi
    fi

script:
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir -p build && cd build
  - export CMAKE_OPTIONS="-DCMAKE_CXX_STANDARD=11 -DBLA_VENDOR=$BACKEND"
  - |
    if [[ "${BUILD_STATIC}" == "ON" ]]; then
      export CMAKE_OPTIONS="${CMAKE_OPTIONS} -DBLA_STATIC=ON"
    fi
  - if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then echo $LD_LIBRARY_PATH; fi
  - if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then echo $DYLD_LIBRARY_PATH; fi
  - echo "cmake .. ${CMAKE_OPTIONS}"
  - cmake .. ${CMAKE_OPTIONS}
  - make VERBOSE=1
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      ldd ./CMakeHelloWorld
    else  # Mac
      otool -L ./CMakeHelloWorld
    fi

after_success:
  - ./CMakeHelloWorld

notifications:
  email: false
