sudo: true

language:
  - cpp

cache:
  ccache: true
  directories:
    - $HOME/downloads

matrix:
  include:
    #########
    # Linux Machines
    #########
    - os: linux
      env:
        - BACKEND=Intel10_64lp_seq
        - BUILD_STATIC=OFF
    - os: linux
      env:
        - BACKEND=Intel10_64lp_seq
        - BUILD_STATIC=ON
    - os: linux
      env:
        - BACKEND=Intel10_64lp
        - BUILD_STATIC=OFF
    - os: linux
      env:
        - BACKEND=Intel10_64lp
        - BUILD_STATIC=ON

    #########
    # OSx Machines
    #########
    - os: osx
      env:
        - BACKEND=Intel10_64lp_seq
        - BUILD_STATIC=OFF
    - os: osx
      env:
        - BACKEND=Intel10_64lp_seq
        - BUILD_STATIC=ON
    - os: osx
      env:
        - BACKEND=Intel10_64lp
        - BUILD_STATIC=OFF
    - os: osx
      env:
        - BACKEND=Intel10_64lp
        - BUILD_STATIC=ON


before_install:
  # Dependencies required by the CI are installed in ${TRAVIS_BUILD_DIR}/deps/
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir -p "${DEPS_DIR}"

  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      sudo dpkg --add-architecture i386
      sudo apt-get update
      sudo apt-get install -y libc6:i386 libncurses5:i386 libstdc++6:i386
    fi

  # Travis machines have 2 cores
  - JOBS=2

  - cd "${DEPS_DIR}"

  ############################################################################
  # Handle caching of downloaded files
  ############################################################################
  - export DL_DIR=$HOME/downloads
  - curl -fsSkL https://raw.githubusercontent.com/openmeeg/ci-utils/master/travis/travis_tools.sh > x.sh && source ./x.sh

  ############################################################################
  # Install a recent CMake
  ############################################################################
  - CMAKE_VERSION=3.10.1
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      CMAKE_URL="https://cmake.org/files/v${CMAKE_VERSION%.[0-9]}/cmake-${CMAKE_VERSION}-Linux-x86_64.tar.gz"
      mkdir cmake && travis_retry wget --no-check-certificate -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}
    else
      brew upgrade cmake
    fi
  - which cmake
  - cmake --version

  ############################################################################
  # Install MKL
  ############################################################################
  - |
    if [[ "${BACKEND}" == *"Intel"* ]]; then
      curl -fsSkL https://raw.githubusercontent.com/openmeeg/ci-utils/master/travis/install_mkl.sh > install_mkl.sh && source ./install_mkl.sh
    fi

script:
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir -p build && cd build
  - export CMAKE_OPTIONS="-DCMAKE_CXX_STANDARD=11 -DBLA_VENDOR=$BACKEND"
  - |
    if [[ "${BUILD_STATIC}" == "ON" ]]; then
      export CMAKE_OPTIONS="${CMAKE_OPTIONS} -DBLA_STATIC=ON"
    fi
  - if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then echo $LD_LIBRARY_PATH; fi
  - if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then echo $DYLD_LIBRARY_PATH; fi
  - echo "cmake .. ${CMAKE_OPTIONS}"
  - cmake .. ${CMAKE_OPTIONS}
  - make VERBOSE=1
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      ldd ./hello
    else  # Mac
      otool -L ./hello
    fi

after_success:
  - ./hello

notifications:
  email: false
